// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // ensure the datasource object matches the exactOptionalPropertyTypes expectations
  datasource: (() => {
    const ds: { url?: string; shadowDatabaseUrl?: string } = {};
    if (process.env.DATABASE_URL) ds.url = process.env.DATABASE_URL;
    return ds;
  })(),
});
